GET http://localhost:3000/product/getproducts
###
GET http://localhost:3000/user/getuser   
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0971717171",
  "password":"Yasub1234"
}

###
POST http://localhost:3000/product/addproduct
Authorization: Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzdWIiLCJwaG9uZSI6IjA5NzE3MTcxNzEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRUQ0RWMnlQUnpqRUhlQzhVLy9nNkxPL0k5NkJjWWRrRWVFbG94akQuOHNoeHlEdXdvWmFCVyIsImFnZSI6MjIsImlhdCI6MTcyMzU1NTgwNSwiZXhwIjoxNzIzNTU2NDA1fQ.gWWj0dicrWADcyjRIMYyxecGRcyydYrYltXpGA_X5Hc
Content-Type: application/json

{
  "name":"water",
  "price":10,
  "productId":"wa",
  "category":"other"
}