GET http://localhost:3000/product/getproducts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyNDQzNDUxOCwiZXhwIjoxNzI0NDM2MzE4fQ.ON5t5R8s2cISztHxh7hvR1herQ0dq_P5JgWPzzrcSoc
###
GET http://localhost:3000/user/getuser   
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0987324228",
  "password":"Kirubel1995"
}

###
POST http://localhost:3000/product/addproduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyNDQzNDI5NCwiZXhwIjoxNzI0NDM2MDk0fQ.mZeEOEKXFpUp5vya9cbxQYb7jojWC73OmplBe3c4gvo
Content-Type: application/json

{
    "name": "productToCheck",
    "price": 4000,
    "productId": "product1234",
    "category": "clothing",
    "quantity": 15,
    "brand": "nike"
}

###
PATCH  http://localhost:3000/product/editproduct/66bdc548be867904979934c1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInBob25lIjoiMDk4NzMyNDIyOCIsInJvbGUiOiJBZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEpVanE1LkhIZGx4UkFOM2J6b1JJUi5Ob2wvUWpsNU1VNS8ycEpTdi83cmpMYlh6dm1pVzk2IiwiYWdlIjoyMSwiaWF0IjoxNzIzNzEyODkzLCJleHAiOjE3MjM3MTM0OTN9.AsY6levU12OjAwsHNbydKPx8cfs3La4Bm9qAVG_o-k0
Content-Type: application/json

{
  "quantity":5
}

###
DELETE http://localhost:3000/product/deleteproduct/66c8c79e46318bff35c7ad1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyNDQzNDI5NCwiZXhwIjoxNzI0NDM2MDk0fQ.mZeEOEKXFpUp5vya9cbxQYb7jojWC73OmplBe3c4gvo