GET http://localhost:3000/product/getproducts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyMzc5Njc5NiwiZXhwIjoxNzIzNzk4NTk2fQ.HRcax9YnIlMSOHBUADkV66sx4BVaKQ8pa1vqWXaajoc
###
GET http://localhost:3000/user/getuser   
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0987324228",
  "password":"Kirubel1995"
}

###
POST http://localhost:3000/product/addproduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyMzc5NTEyNSwiZXhwIjoxNzIzNzk2OTI1fQ.qDDojk2hrAaEaHq5Gb8OnP-3_8cct96slkXVeoaGjvs
Content-Type: application/json

{
    "name": "tobedeleted",
    "price": 4000,
    "productId": "sth",
    "category": "clothing",
    "quantity": 5,
    "brand": "nike"
}

###
PATCH  http://localhost:3000/product/editproduct/66bdc548be867904979934c1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInBob25lIjoiMDk4NzMyNDIyOCIsInJvbGUiOiJBZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEpVanE1LkhIZGx4UkFOM2J6b1JJUi5Ob2wvUWpsNU1VNS8ycEpTdi83cmpMYlh6dm1pVzk2IiwiYWdlIjoyMSwiaWF0IjoxNzIzNzEyODkzLCJleHAiOjE3MjM3MTM0OTN9.AsY6levU12OjAwsHNbydKPx8cfs3La4Bm9qAVG_o-k0
Content-Type: application/json

{
  "quantity":5
}

###
DELETE http://localhost:3000/product/deleteproduct/66b12ec95e4a1c1e60b0c30a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyMzc5Njc5NiwiZXhwIjoxNzIzNzk4NTk2fQ.HRcax9YnIlMSOHBUADkV66sx4BVaKQ8pa1vqWXaajoc