
GET http://localhost:3000/user/getuser

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0987324228", 
  "password":"Kirubel1995"
}

###

GET http://localhost:3000/user/userprofile/66ad4b0cccd2ed137747d59e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInBob25lIjoiMDk4NzMyNDIyOCIsInJvbGUiOiJBZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEpVanE1LkhIZGx4UkFOM2J6b1JJUi5Ob2wvUWpsNU1VNS8ycEpTdi83cmpMYlh6dm1pVzk2IiwiYWdlIjoyMSwiaWF0IjoxNzIzNTUyNTgyLCJleHAiOjE3MjM1NTMxODJ9.i-aE0lMTOqzUxsOAjVSlIB_ZhmQx3u0wLOE5ZQAEItU


###

DELETE  http://localhost:3000/user/deleteuser/66bb54af89ab1423e513e713
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInBob25lIjoiMDk4NzMyNDIyOCIsInJvbGUiOiJBZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEpVanE1LkhIZGx4UkFOM2J6b1JJUi5Ob2wvUWpsNU1VNS8ycEpTdi83cmpMYlh6dm1pVzk2IiwiYWdlIjoyMSwiaWF0IjoxNzIzNTUzMDA0LCJleHAiOjE3MjM1NTM2MDR9.dij7cfI5NZ6wptpEoVNme_11MUqUNk9Hc9jCrw_TApQ

###
PATCH http://localhost:3000/user/editinfo/66ad4b5eccd2ed137747d5a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJlbmkiLCJwaG9uZSI6IjA5MDAwMDAwMDAiLCJyb2xlIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRYem9sTEQucm5haE9NbS5mZkVMTk11WE84aENaRHV2OS5BMEY4dzB3Nmt2d25FQ0xTeW1uMiIsImFnZSI6MjEsImlhdCI6MTcyMzM4MjEzN30.2BKRpFiVDUhGKkCNNgOlwu5V65wgbpZ2EitRafxN4bU
Content-Type: application/json

{
  "name":"Abeni",
  "phone":"0905050500",
  "password":"Abeni1234"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name":"Dad",
  "phone":"0971717192",
  "role":"Customer",
  "password":"Dad1234",
  "age":40
}