
GET http://localhost:3000/user/getuser

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0971717171", 
  "password":"Yasub1234"
}

###

GET http://localhost:3000/user/userprofile/66b8ad28111c19cf17fd6398
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInBob25lIjoiMDk4NzMyNDIyOCIsInJvbGUiOiJBZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEpVanE1LkhIZGx4UkFOM2J6b1JJUi5Ob2wvUWpsNU1VNS8ycEpTdi83cmpMYlh6dm1pVzk2IiwiYWdlIjoyMSwiaWF0IjoxNzIzMzk2NzMxfQ.FnXBTqWfTfnoJXh4OSyT-LmP1maSe8UWdcd_8pT-Eq4


###

DELETE  http://localhost:3000/user/deleteuser/66bb1d06f78799ca06ba65e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzdWIiLCJwaG9uZSI6IjA5NzE3MTcxNzEiLCJyb2xlIjoiQ3VzdG9tZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRUQ0RWMnlQUnpqRUhlQzhVLy9nNkxPL0k5NkJjWWRrRWVFbG94akQuOHNoeHlEdXdvWmFCVyIsImFnZSI6MjIsImlhdCI6MTcyMzUzODczOCwiZXhwIjoxNzIzNTM5MzM4fQ.1gh12N3Z4OkFQbiONRtFqc2bxwEFKOe1rwhJ6d6953c

###
PATCH http://localhost:3000/user/editinfo/66ad4b5eccd2ed137747d5a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJlbmkiLCJwaG9uZSI6IjA5MDAwMDAwMDAiLCJyb2xlIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRYem9sTEQucm5haE9NbS5mZkVMTk11WE84aENaRHV2OS5BMEY4dzB3Nmt2d25FQ0xTeW1uMiIsImFnZSI6MjEsImlhdCI6MTcyMzM4MjEzN30.2BKRpFiVDUhGKkCNNgOlwu5V65wgbpZ2EitRafxN4bU
Content-Type: application/json

{
  "name":"Abeni",
  "phone":"0905050500",
  "password":"Abeni1234"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name":"Dad",
  "phone":"0971717192",
  "role":"Customer",
  "password":"Dad1234",
  "age":40
}