POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0987324228", 
  "password":"Kirubel1995"
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "phone":"0971717192", 
  "password":"Dad1234"
}
###
GET http://localhost:3000/product/getproducts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyMzcyMTUwOSwiZXhwIjoxNzIzNzIzMzA5fQ.KatmAlnmD9nBh5doNxxebfS0LAmIYEfVFmySeI-PVTQ



###
GET http://localhost:3000/order/getorders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lydWJlbCIsInJvbGUiOiJBZG1pbiIsInVzZXJJZCI6IjY2YWQ0YjBjY2NkMmVkMTM3NzQ3ZDU5ZSIsImlhdCI6MTcyMzcyMTUwOSwiZXhwIjoxNzIzNzIzMzA5fQ.KatmAlnmD9nBh5doNxxebfS0LAmIYEfVFmySeI-PVTQ


###
POST http://localhost:3000/order/createorder
Content-Type: application/json

{
  "userId":"66bb54fd89ab1423e513e71d",
  "totalAmount":10000,
  "orderProducts": [
    {"productId":"66b12ec95e4a1c1e60b0c30a","quantity":10},
    {"productId":"66bb5e289b36a0f5ba5677fa", "quantity":2}
  ]
}

###

GET http://localhost:3000/order/getmyorder
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFkIiwicm9sZSI6IkN1c3RvbWVyIiwidXNlcklkIjoiNjZiYjU0ZmQ4OWFiMTQyM2U1MTNlNzFkIiwiaWF0IjoxNzIzNzIxMzUwLCJleHAiOjE3MjM3MjMxNTB9.55eLxrfZENJQOXOjz8srUa6gNGU21QFhVlDvhHMnRfY

###

PATCH http://localhost:3000/order/editorder
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFkIiwicm9sZSI6IkN1c3RvbWVyIiwidXNlcklkIjoiNjZiYjU0ZmQ4OWFiMTQyM2U1MTNlNzFkIiwiaWF0IjoxNzIzNzIxMzUwLCJleHAiOjE3MjM3MjMxNTB9.55eLxrfZENJQOXOjz8srUa6gNGU21QFhVlDvhHMnRfY
Content-Type: application/json

{
  "totalAmount":"50000"
}